name: CI-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore cached pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  jekyll-build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll:3.8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Jekyll site
        run: jekyll build --config _config.yml,_config-lhci.yml

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  htmlproofer-test:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./_site

      - name: Check HTML with HTMLProofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: --external_only --url_ignore "https://www.cairn.info/commun--9782707186737.htm,https://www.cerveauetpsycho.fr/sd/psychotherapie/il-faut-autoriser-les-therapies-psychedeliques-18929.php,https://www.fun-mooc.fr/fr/cours/fabriquer-linnovation/"

  lighthouse-test:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Keep only Lighthouse config file
        run: find . \! -name '.lighthouserc.js' -delete

      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./_site

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@latest

      - name: Collect LHCI results
        run: lhci collect --config .lighthouserc.js

      - name: Upload LHCI results
        run: lhci upload --config .lighthouserc.js || echo "LHCI upload failed but continuing"

      - name: Assert LHCI results
        run: lhci assert --config .lighthouserc.js
